version: '3.0'

services:
  php:
    container_name: php
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/var/www/html
    networks:
      - network
    depends_on:
      mariadb:
        condition: service_healthy

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 8080:8080
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    networks:
      - network
    depends_on:
      - php

  mariadb:
    container_name: mariadb
    image: mariadb:10.11.2
    restart: on-failure
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
      MARIADB_DATABASE: 'app'
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql
    networks:
      - network
    healthcheck:
      test: ['CMD', 'mysqladmin', '-uroot', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  data:

networks:
  network:
    driver: bridge
