version: '3.0'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/var/www/html
    networks:
      - app_network

  web:
    container_name: web
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    networks:
      - app_network
    depends_on:
      - app

networks:
  app_network:
    driver: bridge
